# Generated by Django 2.2.2 on 2019-10-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('notice_by', models.TextField(blank=True, max_length=500)),
                ('is_important', models.BooleanField()),
            ],
        ),
    ]
