# Generated by Django 2.2.2 on 2019-10-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='heading',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
